### ISSUE TITLE
Worker pool model may not work well with lazy loading certificates

### ISSUE THREAD

**Issue by joshlf** [cloudflare/gokeyless#171]
With @Bren2010 's recent refactor to a worker pool model (one that I intend to keep in my own [`performance`](https://github.com/joshlf/gokeyless/tree/performance) refactor), I am concerned that lazy-loading of certificates in the worker goroutines may be a performance bottleneck.

The model is something like this (what is presented here is true both of @Bren2010 's refactor and of my own work):
* Each connection has its own goroutine that is solely responsible for reading packets off of the connection.
* Once a packet is read, it is sent over a single global channel to a pool of workers.
* The pool has a fixed number of worker goroutines.
* Worker goroutines loop pulling jobs off the channel and doing the associated work. @Bren2010 's design and my own differ in what happens next - whether the worker goroutine writes the result directly to the network connection or sends it over another channel for further processing - but in either case, the worker goroutines represent a latency bottleneck - if any one of them (or multiple of them) stalls for too long on a single job, the average latency of the system could be affected.

Here's where the problem arises: in both of our designs, a key identifier (SNI, SKI, or IP) is sent along with the job definition, and it is the worker goroutine's job to locate the key associated with that identifier. For in-memory keys, this is not a big deal. However, we also support having the key store be an in-memory cache that is backed by some slower storage medium such as disk. In that case, looking up a key which is not in cache can result in disk IO or some other slow operation.

My concern is this: In such a scenario, if a key is requested that is not currently in cache, it could result in a worker goroutine taking tens of milliseconds or more on a job when the normal runtime is in the tens of microseconds.

## Solutions
I see a couple of possible solutions to this. They all involve making it somebody else's responsibility (besides the worker goroutine) to load the key into memory:
* The goroutine reading packets off the network connection is responsible for loading keys. This makes it so that a slow key load won't affect the latency of other connections in the system, but it will still adversely affect this connection.
* The goroutine reading packets off the network connection spawns a new goroutine. That new goroutine loads the key and then sends the job to the worker pool. This addresses the problem of the previous approach, but means that every job must spawn a new goroutine even if the key is already in memory.
* A hybrid approach: The reading goroutine first checks to see if the key is in the memory cache. If it is, the reading goroutine sends it along with the job directly. If not, it spawns a new goroutine to load the key as in the previous model.

**Comment by joshlf** [comment]
Come to think of it, spawning goroutines introduces a memory leak risk - an attacker could send requests faster than we can process them, which would result in a large number of goroutines being spawned. The channel supplying the pool with jobs would eventually back up, at which point all of the spawned goroutines would be blocked on sending and unable to die. The reader goroutine would continue reading packets off the connection and spawning goroutines until the system ran out of memory.

**Comment by joshlf** [comment]
I suppose that one approach would be to have a maximum number of outstanding requests (or even just a maximum number of outstanding key lookups) per connection and blocking if you reach that maximum.

**Comment by Bren2010** [comment]
> I suppose that one approach would be to have a maximum number of outstanding requests

You could say that the number of workers in the pool is this parameter, so from the latency point-of-view a worker pool is optimal because we don't have to create new goroutines and wait for them to get scheduled.

From a throughput point-of-view: Assuming we want to handle 1,000 req/s (a huge number) and that different workers are truly parallel, then the most expensive operation needs to happen in less than 8 milliseconds. This sounds like a sufficient amount of to me.

If you want to add a metric that somehow measures "typical number of busy/idle worker threads", I think that would valuable for making sure we are using the right model. Although I imagine that 8 workers is more-than-sufficient for now.

**Comment by joshlf** [comment]
> You could say that the number of workers in the pool is this parameter, so from the latency point-of-view a worker pool is optimal because we don't have to create new goroutines and wait for them to get scheduled.

This is an interesting thought, although my concern would be that, just like the issue of generating random ECDSA values in the worker threads as opposed to in an idle thread, you'd run the risk that at the moment a request came in, all of the worker threads were in the middle of a long-running (IO-bound, in this case) computation, and so the latency would be high due to waiting for the first one to finish its computation and be ready to process the request.

**Comment by joshlf** [comment]
> If you want to add a metric that somehow measures "typical number of busy/idle worker threads", I think that would valuable for making sure we are using the right model.

I'm not sure how that'd be done, but I think it's a good idea.

**Comment by cbroglie** [comment]
This has proven to be a non-issue in practice
