### ISSUE TITLE
Fix logging for cmd/gokeyless

### ISSUE THREAD

**Issue by joshlf** [cloudflare/gokeyless#196]
The `cmd/gokeyless` `-loglevel` flag has no effect because of weird effects of vendoring.

**Comment by lziest** [comment]
I am not able to replicate it.
I use `go get -u github.com/cloudflare/gokeyless/cmd/gokeyless`, and it works fine, `-loglevel` controls the log level. 😕

**Comment by joshlf** [comment]
Fair enough.
