### ISSUE TITLE
Set GOMAXPROCS on package build time

### ISSUE THREAD

**Issue by jacobhaven** [cloudflare/gokeyless#21]
Increasing the `GOMAXPROCS` from the default could increase the ability to concurrently handle requests.

**Comment by elithrar** [comment]
This should no longer be needed as Go >=1.5 automatically sets `GOMAXPROCS` to the value of `runtime.NumCPU`.

**Comment by jacobhaven** [comment]
Good point. I realized this a while ago, and so never touched this issue.
