### ISSUE TITLE
Don't start service during package installation

### ISSUE THREAD

**Issue by joshlf** [cloudflare/gokeyless#210]
Currently, at least with the .deb artifact (I haven't tested with .rpm), when we install gokeyless as a package, the service is automatically started. However, gokeyless needs manual configuration, so the service just fails and is left in a bad state.

We should instead make it so that the service is not started during installation. Currently, this is not an option in `fpm`, the tool we use to generate packages. Thus, this issue is blocked on https://github.com/jordansissel/fpm/issues/1363.

**Comment by cbroglie** [comment]
This has been mitigated by #226 and #231
