### ISSUE TITLE
Sporadic test failure in TestClientBlocks

### ISSUE THREAD

**Issue by Lekensteyn** [cloudflare/gokeyless#255]
There is possible a race condition which results in a test failure:
```
=== RUN   TestClientBlocks
--- FAIL: TestClientBlocks (0.09s)
	client_test.go:137: job not submitted
...
FAIL	github.com/cloudflare/gokeyless/server/internal/client	1.361s
```
From https://travis-ci.org/Lekensteyn/gokeyless/jobs/509410009

This has so far occurred only once with the Go 1.10 environment.

**Comment by nickysemenza** [comment]
closing this as stale, haven't seen this in recent memory / on github actions
