### ISSUE TITLE
Gokeyless not support crypto user(cu) for HSM IBM

### ISSUE THREAD

**Issue by Ruksov-Andrey** [cloudflare/gokeyless#302]
This is the declared feature. https://developers.cloudflare.com/ssl/keyless-ssl/hardware-security-modules/ibm-cloud-hsm/#4-modify-your-gokeyless-config-file-and-restart-the-service

It supports crypto officer (co)

[FATAL] failed to log into long term session: pkcs11: 0xA0: CKR_PIN_INCORRECT

https://github.com/ThalesIgnite/crypto11/commit/026f79660ad4ee406a0f23056bd6e0fd6fd723b3

**Comment by nickysemenza** [comment]
Hi, our `go.mod` specifies `github.com/ThalesIgnite/crypto11 v1.2.1`, but it looks like that was added in `v1.2.5`. The version can certainly be bumped
