### ISSUE TITLE
Kubernetes Support

### ISSUE THREAD

**Issue by ortegaantunes** [cloudflare/gokeyless#319]
Hi

Does someone already deploy the gokeyless in a Kubernetes cluster? If yes, is there any different approach to take or even slight configurations to have in mind?

I've been trying to deploy it in an AKS Cluster, but I'm facing some weird issues related to the PID creation as well as getting errors like `cannot parse 'port' as int: strconv.ParseInt: parsing "tcp://X.X.X.X:2407": invalid syntax` 

Sorry if this is not the correct place for this kind of question.

Thanks in advance

**Comment by nickysemenza** [comment]
it should work out of the box - sounds like you're providing `"tcp://X.X.X.X:2407` in the config where it expects `2407` perhaps?

**Comment by ortegaantunes** [comment]
The issue was related to the service name. Nothing related to the application itself
