### ISSUE TITLE
Manual activation should admit provisioning by configuration file or environment variable

### ISSUE THREAD

**Issue by jkroll-cf** [cloudflare/gokeyless#50]
In setting up a keyless server with the new `-manual-activation` flag, one must be able to enter the hostname and API token into a prompt. This makes automation with scripts or deployment on a cluster challenging.

**Comment by jacobhaven** [comment]
Manual activation requires manual action (copying a CSR, sending it to CF and saving the resulting certificate).

Either the resulting server cert/key pair should be deployed or normal provisioning (via the certificateAPI) should be used (pre-creating a `token.json` and deploying that)

**Comment by jkroll-cf** [comment]
The scenario I'm thinking of, which I encountered, is deploying the keyless server in an environment where I'm not attached to provide the prompt answers but do want it to spit out a CSR for me to get signed manually. It should be possible to feed the prompts some other way in this case, such as with a flag, environment variable, or config file.

**Comment by elithrar** [comment]
You could locally run gokeyless -manual-activation - get/sign the CSR - and
then COPY that key.pem and the resulting server.pem into your Docker image.

**Comment by jkroll-cf** [comment]
That's a good point - on reflection, I suppose there's not currently a need for this. However, having it would make the manual activation path more scriptable (although that's what the automated activation path is for).
